version: '3.9'

networks:
  monitoring-net:
    driver: bridge

services:
  backend-app:
    container_name: backend_couriersync_app
    image: bck-couriersync-app:1.0.0
    build: .
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      SERVER_PORT: "${SERVER_PORT}"
      FRONTEND_BASE_URL: "${FRONTEND_BASE_URL}"
      BACKEND_BASE_URL: "${BACKEND_BASE_URL}"
      DB_NAME: "${DB_NAME}"
      DB_HOST: "${DB_HOST}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_PORT: "${DB_PORT}"
      JWT_SECRET: "${JWT_SECRET}"
      JWT_EXPIRATION: "${JWT_EXPIRATION}"
      OAUTH2_IDCLIENT: "${OAUTH2_IDCLIENT}"
      OAUTH2_SECRETCLIENT: "${OAUTH2_SECRETCLIENT}"
      ADMIN_EMAIL: "${ADMIN_EMAIL}"
    networks:
      - monitoring-net

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring-net

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - monitoring-net